module.exports = function(app) {
	var familytree = require('../controllers/familytree.server.controller');
    app.route('/familytree')
        .get(familytree.renderPage1);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-1')
    	.get(familytree.renderPage1);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-2')
    	.get(familytree.renderPage2);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-3')
    	.get(familytree.renderPage3);
     app.route('/familytree/cilliers_niehaus_family_scrapbook-3')
    	.get(familytree.renderPage3);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-3')
    	.get(familytree.renderPage3);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-4')
    	.get(familytree.renderPage4);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-5')
    	.get(familytree.renderPage5);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-6')
    	.get(familytree.renderPage6);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-7')
    	.get(familytree.renderPage7);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-8')
    	.get(familytree.renderPage8);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-9')
    	.get(familytree.renderPage9);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-10')
    	.get(familytree.renderPage10);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-11')
    	.get(familytree.renderPage11);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-12')
    	.get(familytree.renderPage12);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-13')
    	.get(familytree.renderPage13);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-14')
    	.get(familytree.renderPage14);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-15')
    	.get(familytree.renderPage15);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-16')
    	.get(familytree.renderPage16);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-17')
    	.get(familytree.renderPage17);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-18')
    	.get(familytree.renderPage18);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-19')
    	.get(familytree.renderPage19);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-20')
    	.get(familytree.renderPage20);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-21')
    	.get(familytree.renderPage21);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-22')
    	.get(familytree.renderPage22);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-23')
    	.get(familytree.renderPage23);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-24')
    	.get(familytree.renderPage24);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-25')
    	.get(familytree.renderPage25);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-26')
    	.get(familytree.renderPage26);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-27')
    	.get(familytree.renderPage27);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-28')
    	.get(familytree.renderPage28);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-29')
    	.get(familytree.renderPage29);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-30')
    	.get(familytree.renderPage30);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-31')
    	.get(familytree.renderPage31); 
    app.route('/familytree/cilliers_niehaus_family_scrapbook-32')
    	.get(familytree.renderPage32);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-33')
    	.get(familytree.renderPage33);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-34')
    	.get(familytree.renderPage34);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-35')
    	.get(familytree.renderPage35);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-36')
    	.get(familytree.renderPage36);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-37')
    	.get(familytree.renderPage37);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-38')
    	.get(familytree.renderPage38);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-39')
    	.get(familytree.renderPage39);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-40')
    	.get(familytree.renderPage40);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-41')
        .get(familytree.renderPage41);
    app.route('/familytree/cilliers_niehaus_family_scrapbook-42')
        .get(familytree.renderPage42);
};